import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <iframe src="https://video.laacgolf.com/index.html?id=laac&lang=en" className="video" scrolling="no">
          <p>Your browser does not support iframes.</p>
        </iframe>
      </main>
    </div >
  )
}

export default Home
